custom:
  clash_rule_base: https://raw.githubusercontent.com/MillerArice/Clash/refs/heads/main/config/clash_adg_base.yml
  enable_rule_generator: false
  overwrite_original_rules: false
  proxy_groups:
    - name: "🎲 手动选择"
      type: select
      rule: ["[]全球自动", "[]香港自动", "[]日本自动", "[]台湾自动", "[]新加坡自动", "[]美国自动", ".*", "[]DIRECT"]
    - name: "🎥 YouTube"
      type: select
      rule: ["[]🎲 手动选择", "[]全球自动", "[]香港自动", "[]日本自动", "[]台湾自动", "[]新加坡自动", "[]美国自动", ".*"]
    - name: "✈️ 代理补充"
      type: select
      rule: ["[]🎲 手动选择", "[]全球自动", "[]香港自动", "[]日本自动", "[]台湾自动", "[]新加坡自动", "[]美国自动", ".*"]
    - name: "🎮 Steam"
      type: select
      rule: ["[]DIRECT", "[]🎲 手动选择", "[]全球自动", "[]香港自动", "[]日本自动", "[]台湾自动", "[]新加坡自动", "[]美国自动"]
    - name: "🤖 Ai服务"
      type: select
      rule: ["[]🎲 手动选择", "[]全球自动", "[]香港自动", "[]日本自动", "[]台湾自动", "[]新加坡自动", "[]美国自动", ".*"]
    - name: "📲 电报信息"
      type: select
      rule: ["[]🎲 手动选择", "[]全球自动", "[]香港自动", "[]日本自动", "[]台湾自动", "[]新加坡自动", "[]美国自动", ".*"]
    - name: "🎵 TikTok"
      type: select
      rule: ["[]🎲 手动选择", "[]全球自动", "[]香港自动", "[]日本自动", "[]台湾自动", "[]新加坡自动", "[]美国自动"]
    - name: "🎞️ 国外媒体"
      type: select
      rule: ["[]🎲 手动选择", "[]全球自动", "[]香港自动", "[]日本自动", "[]台湾自动", "[]新加坡自动", "[]美国自动"]
    - name: "🌎 私域域名"
      type: select
      rule: ["[]DIRECT", "[]🎲 手动选择", "[]全球自动", "[]香港自动", "[]日本自动", "[]台湾自动", "[]新加坡自动", "[]美国自动"]
    - name: "🏍️ 直连补充"
      type: select
      rule: ["[]DIRECT"]
    - name: "🍎 苹果服务"
      type: select
      rule: ["[]DIRECT"]
    - name: "🎬 国内媒体"
      type: select
      rule: ["[]DIRECT"]
    - name: "🌄 Adobe"
      type: select
      rule: ["[]REJECT"]
    - name: "🎯 全球直连"
      type: select
      rule: ["[]DIRECT"]
    - name: "🐠 漏网之鱼"
      type: select
      rule: ["[]🎲 手动选择", "[]全球自动", "[]香港自动", "[]日本自动", "[]台湾自动", "[]新加坡自动", "[]美国自动"]

    - name: "全球自动"
      type: url-test
      rule: [".*"]
      url: http://www.gstatic.com/generate_204
      interval: 900
      tolerance: 50
    - name: "香港自动"
      type: url-test
      rule: ["(?i)(香港|HK|HKG|Hong.?Kong|🇭🇰)"]
      url: http://www.gstatic.com/generate_204
      interval: 900
      tolerance: 50
    - name: "台湾自动"
      type: url-test
      rule: ["(?i)(台湾|台灣|台北|TW|TWN|Taiwan|Taipei|🇹🇼)"]
      url: http://www.gstatic.com/generate_204
      interval: 900
      tolerance: 50
    - name: "日本自动"
      type: url-test
      rule: ["(?i)(日本|东京|東京|大阪|JP|JPN|Japan|Tokyo|Osaka|🇯🇵)"]
      url: http://www.gstatic.com/generate_204
      interval: 900
      tolerance: 50
    - name: "新加坡自动"
      type: url-test
      rule: ["(?i)(新加坡|狮城|獅城|SG|SGP|Singapore|🇸🇬)"]
      url: http://www.gstatic.com/generate_204
      interval: 900
      tolerance: 50
    - name: "美国自动"
      type: url-test
      rule: ["(?i)(美国|美國|洛杉矶|洛杉磯|纽约|紐約|西雅图|西雅圖|硅谷|US|USA|United.?States|America|🇺🇸)"]
      url: http://www.gstatic.com/generate_204
      interval: 900
      tolerance: 50
