custom:
  clash_rule_base: "https://raw.githubusercontent.com/MillerArice/Clash/refs/heads/main/config/clash_adg_base.yml"
  enable_rule_generator: true
  overwrite_original_rules: true

  rulesets:
    - group: "🏍️ 直连补充"
      ruleset: "https://raw.githubusercontent.com/MillerArice/Clash/refs/heads/main/DIRECT.list"
    - group: "✈️ 代理补充"
      ruleset: "https://raw.githubusercontent.com/MillerArice/Clash/refs/heads/main/PROXY.list"
    - group: "🌎 私域域名"
      ruleset: "https://raw.githubusercontent.com/MillerArice/Clash/refs/heads/main/Domain.list"
    - group: "🎯 全球直连"
      ruleset: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/LocalAreaNetwork.list"
    - group: "🎯 全球直连"
      ruleset: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/UnBan.list"
    - group: "🎯 全球直连"
      ruleset: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/GoogleCN.list"
    - group: "🎯 全球直连"
      ruleset: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/SteamCN.list"
    - group: "🎮 Steam"
      ruleset: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Steam.list"
    - group: "🤖 Ai服务"
      ruleset: "https://raw.githubusercontent.com/MillerArice/Clash/refs/heads/main/OtherAI.list"
    - group: "🍎 苹果服务"
      ruleset: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Apple.list"
    - group: "📲 电报信息"
      ruleset: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Telegram.list"
    - group: "🎥 YouTube"
      ruleset: "https://raw.githubusercontent.com/MillerArice/Clash/refs/heads/main/Youtube.list"
    - group: "🎵 TikTok"
      ruleset: "https://raw.githubusercontent.com/MillerArice/Clash/refs/heads/main/TikTok.list"
    - group: "🎬 国内媒体"
      ruleset: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaMedia.list"
    - group: "🎞️ 国外媒体"
      ruleset: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ProxyMedia.list"
    - group: "🌄 Adobe"
      ruleset: "https://raw.githubusercontent.com/MillerArice/Clash/refs/heads/main/Adobe.list"
    - group: "🎲 手动选择"
      ruleset: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ProxyGFWlist.list"
    - group: "🎯 全球直连"
      ruleset: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaDomain.list"
    - group: "🎯 全球直连"
      ruleset: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaCompanyIp.list"
    - group: "🎯 全球直连"
      ruleset: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Download.list"
    - group: "🎯 全球直连"
      rule: "GEOIP,CN"
    - group: "🐠 漏网之鱼"
      rule: "FINAL"

  proxy_groups:
    - name: "🎲 手动选择"
      type: "select"
      rule: ["[]全球自动", "[]香港自动", "[]日本自动", "[]台湾自动", "[]新加坡自动", "[]美国自动", ".*", "[]DIRECT"]
    - name: "🎥 YouTube"
      type: "select"
      rule: ["[]🎲 手动选择", "[]全球自动", "[]香港自动", "[]日本自动", "[]台湾自动", "[]新加坡自动", "[]美国自动", ".*"]
    - name: "✈️ 代理补充"
      type: "select"
      rule: ["[]🎲 手动选择", "[]全球自动", "[]香港自动", "[]日本自动", "[]台湾自动", "[]新加坡自动", "[]美国自动", ".*"]
    - name: "🎮 Steam"
      type: "select"
      rule: ["[]DIRECT", "[]🎲 手动选择", "[]全球自动", "[]香港自动", "[]日本自动", "[]台湾自动", "[]新加坡自动", "[]美国自动"]
    - name: "🤖 Ai服务"
      type: "select"
      rule: ["[]🎲 手动选择", "[]全球自动", "[]香港自动", "[]日本自动", "[]台湾自动", "[]新加坡自动", "[]美国自动", ".*"]
    - name: "📲 电报信息"
      type: "select"
      rule: ["[]🎲 手动选择", "[]全球自动", "[]香港自动", "[]日本自动", "[]台湾自动", "[]新加坡自动", "[]美国自动", ".*"]
    - name: "🎵 TikTok"
      type: "select"
      rule: ["[]🎲 手动选择", "[]全球自动", "[]香港自动", "[]日本自动", "[]台湾自动", "[]新加坡自动", "[]美国自动"]
    - name: "🎞️ 国外媒体"
      type: "select"
      rule: ["[]🎲 手动选择", "[]全球自动", "[]香港自动", "[]日本自动", "[]台湾自动", "[]新加坡自动", "[]美国自动"]
    - name: "🌎 私域域名"
      type: "select"
      rule: ["[]DIRECT", "[]🎲 手动选择", "[]全球自动", "[]香港自动", "[]日本自动", "[]台湾自动", "[]新加坡自动", "[]美国自动"]
    - name: "🏍️ 直连补充"
      type: "select"
      rule: ["[]DIRECT"]
    - name: "🍎 苹果服务"
      type: "select"
      rule: ["[]DIRECT"]
    - name: "🎬 国内媒体"
      type: "select"
      rule: ["[]DIRECT"]
    - name: "🌄 Adobe"
      type: "select"
      rule: ["[]REJECT"]
    - name: "🎯 全球直连"
      type: "select"
      rule: ["[]DIRECT"]
    - name: "🐠 漏网之鱼"
      type: "select"
      rule: ["[]🎲 手动选择", "[]全球自动", "[]香港自动", "[]日本自动", "[]台湾自动", "[]新加坡自动", "[]美国自动"]

    - name: "全球自动"
      type: "url-test"
      rule: [".*"]
      url: "http://www.gstatic.com/generate_204"
      interval: 300
      tolerance: 50
    - name: "香港自动"
      type: "url-test"
      rule: ["(广港|香港|HK|Hong Kong|🇭🇰|HongKong)"]
      url: "http://www.gstatic.com/generate_204"
      interval: 300
      tolerance: 50
    - name: "台湾自动"
      type: "url-test"
      rule: ["(广台|台湾|台灣|TW|Tai Wan|🇹🇼|🇨🇳|TaiWan|Taiwan)"]
      url: "http://www.gstatic.com/generate_204"
      interval: 300
      tolerance: 50
    - name: "日本自动"
      type: "url-test"
      rule: ["(广日|日本|JP|川日|东京|大阪|泉日|埼玉|沪日|深日|🇯🇵|Japan)"]
      url: "http://www.gstatic.com/generate_204"
      interval: 300
      tolerance: 50
    - name: "新加坡自动"
      type: "url-test"
      rule: ["(广新|新加坡|SG|坡|狮城|🇸🇬|Singapore)"]
      url: "http://www.gstatic.com/generate_204"
      interval: 300
      tolerance: 50
    - name: "美国自动"
      type: "url-test"
      rule: ["(广美|美|US|纽约|波特兰|达拉斯|俄勒冈|凤凰城|费利蒙|硅谷|拉斯维加斯|洛杉矶|圣何塞|圣克拉拉|西雅图|芝加哥|🇺🇸|United States)"]
      url: "http://www.gstatic.com/generate_204"
      interval: 300
      tolerance: 50
